[package]
name = "components"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shizen = { version = "*", path = "../shizen" }
shizen-macros = { version = "*", path = "../shizen-macros" }
